CREATE TABLE subjects(
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    subject VARCHAR(32) NOT NULL UNIQUE
);

INSERT INTO subjects (subject) VALUES 
('MATHEMATICS'),
('PHYSICS'),
('CHEMISTRY'),
('BIOLOGY'),
('ENGLISH'),
('HINDI'),
('SANSKRIT'),
('HISTORY'),
('GEOGRAPHY'),
('ECONOMY'),
('POLITICAL SCIENCE'),
('COMPUTER SCIENCE');